/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.AnimalWelfareKitInventoryManagerRole;
import Business.Role.CharityAdminRole;
import Business.Role.CommerceFinanceTeamLedgerRole;
import Business.Role.DisasterReliefKitInventoryManagerRole;
import Business.Role.DonorIndividualRole;
import Business.Role.DonorAdminRole;
import Business.Role.DonorCSRSupervisorRole;
import Business.Role.EducationKitInventoryManagerRole;
import Business.Role.DisasterReliefCharityPOCRole;
import Business.Role.EducationCharityPOCRole;
import Business.Role.AnimalWelfareCharityPOCRole;
import Business.Role.FinanceAdminRole;
import Business.Role.InventoryAdminRole;
import Business.Role.OrphanageCharityPOCRole;
import static Business.Role.Role.RoleType.InventoryAdminRole;
import Business.Role.SystemAdminRole;

//import Business.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import userinterface.AnimalWelfareCharityOrganization.AnimalWelfareCharityPOCWorkAreaJPanel;
import userinterface.AnimalWelfareKitInventoryManagementOrganization.AnimalWelfareKitInventoryManagerWorkAreaJPanel;
import userinterface.CharityAdmin.CharityAdminWorkArea;
import userinterface.DisasterReliefCharityOrganization.DisasterReliefCharityPOCWorkAreaJPanel;
import userinterface.DisasterReliefKitInventoryManagementOrganization.DisasterReliefKitInventoryManagerWorkAreaJPanel;
import userinterface.Donors.DonorWorkAreaJPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;
import userinterface.DonorRegistration.DonorRegistrationJPanel;
import userinterface.Donors.DonorAdminWorkArea;
import userinterface.EducationCharityOrganization.EducationCharityPOCWorkAreaJPanel;
import userinterface.EducationKitInventoryManagementOrganization.EducationKitInventoryManagerWorkAreaJPanel;
import userinterface.FinanceTeam.CommerceFinanceTeamAdminWorkAreaJPanel;
import userinterface.FinanceTeam.CommerceFinanceTeamLedgerWorkAreaJPanel;
import userinterface.InventoryAdmin.InventoryAdminWorkArea;
import userinterface.OrphanageCharityOrganization.OrphanageCharityPOCWorkAreaJPanel;

/**
 *
 * @author rajiv
 */
public class MainJFrame extends javax.swing.JFrame {

    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    UserAccount userAccount;
    Enterprise enterprise;
    Organization organization;
    Network network;
    /**
     * Creates new form MainJFrame
     */

    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        EcoSystem.setInstance(system);
        this.setSize(1680, 1050);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        loginJButton = new javax.swing.JButton();
        userNameJTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel = new javax.swing.JLabel();
        logoutJButton = new javax.swing.JButton();
        loginError = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(311, 645));

        loginJButton.setText("Login");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        logoutJButton.setText("Logout");
        logoutJButton.setEnabled(false);
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        loginError.setForeground(new java.awt.Color(255, 51, 51));

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(loginJLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginError)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(loginJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(loginJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginError)
                .addGap(18, 18, 18)
                .addComponent(loginJButton)
                .addGap(28, 28, 28)
                .addComponent(logoutJButton)
                .addGap(37, 37, 37)
                .addComponent(btnRegister)
                .addGap(244, 244, 244))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        // Get user name
        String userName = userNameJTextField.getText();
        String password = new String(passwordField.getPassword());

        userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        enterprise = null;
        organization = null;
        network = null;

        if (userAccount == null) {
            for (Network n : system.getNetworkList()) {
                for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                    userAccount = e.getUserAccountDirectory().authenticateUser(userName, password);
                    network = n;
                    if (userAccount == null) {
                        for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                            userAccount = org.getUserAccountDirectory().authenticateUser(userName, password);
                            if (userAccount != null) {
                                enterprise = e;
                                organization = org;
                                network = n;
                                break;
                            }
                        }

                    } else {
                        enterprise = e;
                        break;
                    }
                    if (organization != null) {
                        break;
                    }
                }
                if (enterprise != null) {
                    break;
                }
            }
        }
        if (userAccount == null) {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        } else {
            container.setVisible(true);
            logoutJButton.setEnabled(true);
            userNameJTextField.setEnabled(false);
            passwordField.setEnabled(false);
            loginJButton.setEnabled(false);
            btnRegister.setEnabled(false);
            userNameJTextField.setText("");
            passwordField.setText("");
            changePanel();
        }
        

    }//GEN-LAST:event_loginJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        //dB4OUtil.storeSystem(system);
        logoutJButton.setEnabled(false);
        logoutJButton.setText("Logout");
        btnRegister.setEnabled(true);
        userNameJTextField.setEnabled(true);
        passwordField.setEnabled(true);
        loginJButton.setEnabled(true);

        userNameJTextField.setText("");
        passwordField.setText("");

        userNameJTextField.setText("");
        passwordField.setText("");
        jSplitPane1.setRightComponent(container);
    }//GEN-LAST:event_logoutJButtonActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        DonorRegistrationJPanel panel = new DonorRegistrationJPanel(container, system);
        jSplitPane1.setRightComponent(panel);
        container.setVisible(true);
            logoutJButton.setEnabled(true);
            logoutJButton.setText("Back to home");
            userNameJTextField.setEnabled(false);
            passwordField.setEnabled(false);
            loginJButton.setEnabled(false);
            btnRegister.setEnabled(false);
            userNameJTextField.setText("");
            passwordField.setText("");
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void changePanel() {

        if (userAccount != null && userAccount.getRole() != null) {
            String greetings = "Hi";
            if (userAccount.getRole() instanceof SystemAdminRole) {
                greetings = greetings + " " + userAccount.getUsername();
                SystemAdminWorkAreaJPanel admin = new SystemAdminWorkAreaJPanel(container, system);
                jSplitPane1.setRightComponent(admin);
            } 
            else if(userAccount.getRole() instanceof DonorAdminRole) {
                DonorAdminWorkArea panel = new DonorAdminWorkArea(container, system, network, enterprise, userAccount);
                jSplitPane1.setRightComponent(panel);
            } 
            else if(userAccount.getRole() instanceof DonorCSRSupervisorRole) {
                DonorWorkAreaJPanel panel = new DonorWorkAreaJPanel(container, system, userAccount, network, enterprise);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof DonorIndividualRole) {
                DonorWorkAreaJPanel panel = new DonorWorkAreaJPanel(container, system, userAccount, network, enterprise);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof CharityAdminRole) {
                CharityAdminWorkArea panel = new CharityAdminWorkArea( container, system, network, enterprise);
                jSplitPane1.setRightComponent(panel);
            } 
            else if(userAccount.getRole() instanceof AnimalWelfareCharityPOCRole) {
                AnimalWelfareCharityPOCWorkAreaJPanel panel = new AnimalWelfareCharityPOCWorkAreaJPanel(userAccount,enterprise,organization, network);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof DisasterReliefCharityPOCRole) {
                DisasterReliefCharityPOCWorkAreaJPanel panel = new DisasterReliefCharityPOCWorkAreaJPanel(userAccount,enterprise,organization);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof EducationCharityPOCRole) {
                EducationCharityPOCWorkAreaJPanel panel = new EducationCharityPOCWorkAreaJPanel(userAccount,enterprise,organization, network);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof OrphanageCharityPOCRole) {
                OrphanageCharityPOCWorkAreaJPanel panel = new OrphanageCharityPOCWorkAreaJPanel(userAccount,enterprise,organization);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof InventoryAdminRole) {
                InventoryAdminWorkArea panel = new InventoryAdminWorkArea(container, system, network, enterprise, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof AnimalWelfareKitInventoryManagerRole) {
                AnimalWelfareKitInventoryManagerWorkAreaJPanel panel = new AnimalWelfareKitInventoryManagerWorkAreaJPanel(userAccount,enterprise,organization);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof DisasterReliefKitInventoryManagerRole) {
                DisasterReliefKitInventoryManagerWorkAreaJPanel panel = new DisasterReliefKitInventoryManagerWorkAreaJPanel(container, system, network, enterprise);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof EducationKitInventoryManagerRole) {
                EducationKitInventoryManagerWorkAreaJPanel panel = new EducationKitInventoryManagerWorkAreaJPanel(userAccount,enterprise,organization);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof FinanceAdminRole) {
                CommerceFinanceTeamAdminWorkAreaJPanel panel = new CommerceFinanceTeamAdminWorkAreaJPanel(container, system, network, enterprise, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
            else if(userAccount.getRole() instanceof CommerceFinanceTeamLedgerRole) {
                CommerceFinanceTeamLedgerWorkAreaJPanel panel = new CommerceFinanceTeamLedgerWorkAreaJPanel(container, system, network, enterprise, userAccount);
                jSplitPane1.setRightComponent(panel);
            }
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel loginError;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel loginJLabel;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameJTextField;
    // End of variables declaration//GEN-END:variables
}
