/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface.Donors;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utilities.Validation;
import Business.WorkQueue.CommerceFinanceRequest;
import Business.WorkQueue.WorkQueue;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author nanditasharma
 */
public class DonateFunds extends javax.swing.JFrame {

    Validation validation;
    private static UserAccount account;
    private static Network network;
    private static Enterprise enterprise;
    /**
     * Creates new form DonateFunds
     */
    public DonateFunds(UserAccount account, Network network, Enterprise enterprise) {
        initComponents();
        validation = new Validation();
        this.account = account;
        this.network = network;
        this.enterprise = enterprise;
        populateOrganizationList();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        comboBoxOrg = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnDonate = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPurpose = new javax.swing.JTextField();
        comboBoxCurrency = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 750));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Marker Felt", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 55, 108));
        jLabel1.setText("Donate Funds");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(245, 52, 237, 47);

        comboBoxOrg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxOrg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxOrg);
        comboBoxOrg.setBounds(370, 140, 264, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 55, 108));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Organisation");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 144, 160, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 55, 108));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Amount");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 417, 130, 40);

        txtAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAmountKeyPressed(evt);
            }
        });
        jPanel1.add(txtAmount);
        txtAmount.setBounds(370, 410, 264, 50);

        btnDonate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PictureUI/Donate img.PNG"))); // NOI18N
        btnDonate.setText("Donate");
        btnDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonateActionPerformed(evt);
            }
        });
        jPanel1.add(btnDonate);
        btnDonate.setBounds(440, 490, 130, 140);

        jButton2.setBackground(new java.awt.Color(2, 55, 108));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 12, 90, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(2, 55, 108));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Currency");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 315, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 55, 108));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Purpose");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 221, 130, 40);

        txtPurpose.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtPurpose);
        txtPurpose.setBounds(370, 220, 264, 50);

        comboBoxCurrency.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U.S. Dollar (USD)", "European Euro (EUR)", "British Pound (GBP)", "Canadian Dollar (CAD)", "Indian rupee (INR)" }));
        jPanel1.add(comboBoxCurrency);
        comboBoxCurrency.setBounds(370, 310, 264, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyPressed
        // TODO add your handling code here:
        validation.doubleValidator(evt, txtAmount);
        
    }//GEN-LAST:event_txtAmountKeyPressed

    private void btnDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonateActionPerformed
        // TODO add your handling code here:
        Organization organization = (Organization) comboBoxOrg.getSelectedItem();
        Organization.Type type = organization.getType();

        if (type == null) {
            comboBoxOrg.setBorder(BorderFactory.createLineBorder(Color.RED));
            comboBoxOrg.setForeground(Color.red);
        }

        if (txtAmount.getText().isEmpty()) {
            txtAmount.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtAmount.setForeground(Color.red);
        }

        if (txtAmount.getText().isEmpty() || type == null) {
            JOptionPane.showMessageDialog(null, "Kindly Provide all the Details!");
        } else {
            txtAmount.setBorder(BorderFactory.createLineBorder(Color.black));

            CommerceFinanceRequest commerceFinanceRequest = new CommerceFinanceRequest();
            if(comboBoxCurrency.getSelectedItem().equals("European Euro (EUR)")){
                commerceFinanceRequest.setAmount(Double.parseDouble(txtAmount.getText())*1.13);
            }
            else if(comboBoxCurrency.getSelectedItem().equals("British Pound (GBP)")){
                commerceFinanceRequest.setAmount(Double.parseDouble(txtAmount.getText())*1.32);
            }
            else if(comboBoxCurrency.getSelectedItem().equals("Canadian Dollar (CAD)")){
                commerceFinanceRequest.setAmount(Double.parseDouble(txtAmount.getText())*0.78);
            }
            else if(comboBoxCurrency.getSelectedItem().equals("Indian rupee (INR)")){
                commerceFinanceRequest.setAmount(Double.parseDouble(txtAmount.getText())*0.013);
            }
            else{
                commerceFinanceRequest.setAmount(Double.parseDouble(txtAmount.getText()));
            }
            
            commerceFinanceRequest.setDonorName(account.getEmployee().getName());
            commerceFinanceRequest.setDonorType(account.getRole().toString());
            commerceFinanceRequest.setStatus("Donated");
            commerceFinanceRequest.setRequestDate(new Date());
            commerceFinanceRequest.setEnterprise(enterprise);
            commerceFinanceRequest.setNetwork(network);
            commerceFinanceRequest.setOrgType(type);

            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.FinanceManagementDirectory) {
                    for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                        if(org.getType() == Organization.Type.CommerceFinanaceManagementOrganization){
                            if (org.getWorkQueue() == null) {
                            org.setWorkQueue(new WorkQueue());
                        }
                        org.getWorkQueue().getWorkRequestList().add(commerceFinanceRequest);

                        }
                    }
                }
            }
            JOptionPane.showMessageDialog(null, "Thank you for your donation!");
            txtAmount.setText("");
            comboBoxOrg.setSelectedIndex(0);
            txtPurpose.setText("");
            comboBoxCurrency.setSelectedIndex(0);
            close();
        }
    }//GEN-LAST:event_btnDonateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonateFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonateFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonateFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonateFunds.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonateFunds( account,  network, enterprise).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonate;
    private javax.swing.JComboBox<String> comboBoxCurrency;
    private javax.swing.JComboBox comboBoxOrg;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtPurpose;
    // End of variables declaration//GEN-END:variables
    private void populateOrganizationList() {
        comboBoxOrg.removeAllItems();
        
        for(Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()){
            if(e.getEnterpriseType().toString().equals(Enterprise.EnterpriseType.CharityDirectory.toString())){
                for(Organization org : e.getOrganizationDirectory().getOrganizationList()){
                        comboBoxOrg.addItem(org);
                }
            }
                
            
        }
    }
}
