/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.Donors;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Role.DonorCSRSupervisorRole;
import Business.Role.DonorIndividualRole;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorRegistrationRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nanditasharma
 */
public class DonorAdminWorkArea extends javax.swing.JPanel {

    private static JPanel container;
    private static EcoSystem system;
    private static Network network;
    private static Enterprise enterprise;
    private static UserAccount account;
    /**
     * Creates new form DonorAdminWorkArea
     */
    public DonorAdminWorkArea(JPanel container, EcoSystem system, Network network, Enterprise enterprise, UserAccount account) {
        initComponents();

        this.container = container;
        this.system = system;
        this.network = network;
        this.enterprise = enterprise;
        this.account = account;
        populateOrganizationTable();
        populateOrganizationTypes();
        populateTable();
    }
    
    private void populateOrganizationTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrganizationList.getModel();
        
        model.setRowCount(0);
            for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                Object[] row = new Object[1];
                row[0] = org.getName();
                model.addRow(row);
            }
            
        
    }

    public void populateOrganizationTypes() {
        comboBoxOrgType.removeAllItems();
        comboBoxOrgType.addItem(Organization.Type.DonorCSR);
        comboBoxOrgType.addItem(Organization.Type.DonorIndividual);
    }
    
    private void populateWorkRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblWorkQueue.getModel();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise.getEnterpriseType() == Enterprise.EnterpriseType.DonorDirectory){
                        for(WorkRequest wr : enterprise.getWorkQueue().getWorkRequestList()){
                            if(wr instanceof DonorRegistrationRequest){
                                Object[] row = new Object[8];
                                row[0] = wr;
                                row[1] = formatter.format(wr.getRequestDate());
                                row[2] = ((DonorRegistrationRequest) wr).getName();
                                row[3] = ((DonorRegistrationRequest) wr).getOrgType();
                                row[4] = ((DonorRegistrationRequest) wr).getUserAddress();
                                row[5] = ((DonorRegistrationRequest) wr).getUserContact();
                                row[6] = ((DonorRegistrationRequest) wr).getUserEmailId();
                                row[7] = wr.getStatus();

                                model.addRow(row);
                            } 
                            
                        }
                      
                }
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganizationList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxOrgType = new javax.swing.JComboBox();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAddOrganization = new javax.swing.JButton();
        lblDonarName2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWorkQueue = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        lblDonarName1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jTabbedPane1.setForeground(new java.awt.Color(2, 55, 108));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jScrollPane1.setForeground(new java.awt.Color(2, 55, 108));

        tblOrganizationList.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(2, 55, 108)), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(2, 55, 108))));
        tblOrganizationList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganizationList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 888, 194);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(2, 55, 108));
        jLabel1.setText("Organization List");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 152, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 55, 108));
        jLabel2.setText("Organization Type");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 390, 164, 22);

        comboBoxOrgType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        comboBoxOrgType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboBoxOrgType);
        comboBoxOrgType.setBounds(480, 390, 220, 40);

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(txtName);
        txtName.setBounds(480, 440, 220, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(2, 55, 108));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 440, 110, 22);

        btnAddOrganization.setBackground(new java.awt.Color(2, 55, 108));
        btnAddOrganization.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddOrganization.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOrganization.setText("Add Organization");
        btnAddOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrganizationActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddOrganization);
        btnAddOrganization.setBounds(480, 530, 220, 40);

        lblDonarName2.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        lblDonarName2.setForeground(new java.awt.Color(2, 55, 108));
        lblDonarName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonarName2.setText("Welcome Donor Admin");
        jPanel1.add(lblDonarName2);
        lblDonarName2.setBounds(10, 50, 1109, 32);

        jTabbedPane1.addTab("Manage Organization", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        tblWorkQueue.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(2, 55, 108)), javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(2, 55, 108))));
        tblWorkQueue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Request #", "Request Date", "Requestor Name", "Organization Type", "Address", "Contact", "Email Address", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblWorkQueue);
        if (tblWorkQueue.getColumnModel().getColumnCount() > 0) {
            tblWorkQueue.getColumnModel().getColumn(0).setMinWidth(0);
            tblWorkQueue.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblWorkQueue.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 128, 955, 160);

        btnProcess.setBackground(new java.awt.Color(2, 55, 108));
        btnProcess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnProcess.setForeground(new java.awt.Color(255, 255, 255));
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        jPanel2.add(btnProcess);
        btnProcess.setBounds(780, 320, 180, 40);

        btnAssign.setBackground(new java.awt.Color(2, 55, 108));
        btnAssign.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(255, 255, 255));
        btnAssign.setText("Assign to me ");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        jPanel2.add(btnAssign);
        btnAssign.setBounds(580, 320, 180, 40);

        lblDonarName1.setFont(new java.awt.Font("Marker Felt", 1, 24)); // NOI18N
        lblDonarName1.setForeground(new java.awt.Color(2, 55, 108));
        lblDonarName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDonarName1.setText("Welcome Donor Admin");
        jPanel2.add(lblDonarName1);
        lblDonarName1.setBounds(10, 50, 1109, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(2, 55, 108));
        jLabel4.setText("Donor List");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 100, 92, 22);

        jTabbedPane1.addTab("Manage work request", jPanel2);

        add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 91, 1000, 600);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 55, 108));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Donor Admin");
        add(jLabel7);
        jLabel7.setBounds(18, 11, 1116, 67);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/icons8-avatar-64 (15).png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 100, 90);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PictureUI/sysadmin2.jpg"))); // NOI18N
        add(jLabel8);
        jLabel8.setBounds(940, 140, 660, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrganizationActionPerformed
        // TODO add your handling code here:
        String name = txtName.getText().trim();
        Organization.Type type = (Organization.Type) comboBoxOrgType.getSelectedItem();
        if(!name.isEmpty()){
                Organization org = enterprise.getOrganizationDirectory().createOrganization(type, txtName.getText());
                JOptionPane.showMessageDialog(null, "Organization Successfully Created");
                txtName.setText("");
            
        } else{
            JOptionPane.showMessageDialog(null, "Enter Organization name");
        }
        populateOrganizationTable();
    }//GEN-LAST:event_btnAddOrganizationActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkQueue.getSelectedRow();

        if (selectedRow >= 0) {
            DonorRegistrationRequest request = (DonorRegistrationRequest) tblWorkQueue.getValueAt(selectedRow, 0);
            if (request.getStatus().equalsIgnoreCase("Requested")) {
                JOptionPane.showMessageDialog(null, "Please assign request to yourself and then process it.");
                return;
            }
            else{
                
                if (request.getOrgType() == Organization.Type.DonorCSR) {
                System.out.println("Donor CSR");
                for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(org.getType() == Organization.Type.DonorCSR){
                        Employee emp = org.getEmployeeDirectory().createEmployee(request.getName());
                        UserAccount ua1 = org.getUserAccountDirectory().createUserAccount(request.getUserName(), request.getUserPassword(), emp, new DonorCSRSupervisorRole());

                    }
                }
                
            } if (request.getOrgType() == Organization.Type.DonorIndividual) {
                System.out.println("Donor Individual");
                for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if(org.getType() == Organization.Type.DonorIndividual){
                        Employee emp = org.getEmployeeDirectory().createEmployee(request.getName());
                        UserAccount ua1 = org.getUserAccountDirectory().createUserAccount(request.getUserName(), request.getUserPassword(), emp, new DonorIndividualRole());

                    }
                }
                
            } 

            request.setStatus("Completed");
            JOptionPane.showMessageDialog(null, "User account has been activated successfully");
            populateTable();
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Please select a request message to process.");
            return;
        }
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkQueue.getSelectedRow();

        if (selectedRow >= 0) {
            WorkRequest request = (WorkRequest) tblWorkQueue.getValueAt(selectedRow, 0);
            if (request.getStatus().equalsIgnoreCase("Completed")) {
                JOptionPane.showMessageDialog(null, "Request already processed.");
                return;
            }
            else {
                request.setReceiver(account);
                request.setStatus("Pending");
                populateTable();
                JOptionPane.showMessageDialog(null, "Request has successfully assigned");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Choose a request to process.");
            return;
        }
    }//GEN-LAST:event_btnAssignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrganization;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnProcess;
    private javax.swing.JComboBox comboBoxOrgType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDonarName1;
    private javax.swing.JLabel lblDonarName2;
    private javax.swing.JTable tblOrganizationList;
    private javax.swing.JTable tblWorkQueue;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblWorkQueue.getModel();
        SimpleDateFormat formatter = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");

        model.setRowCount(0);

        if (enterprise.getWorkQueue() == null) {
            enterprise.setWorkQueue(new WorkQueue());
        }
        for (WorkRequest workRequest : enterprise.getWorkQueue().getWorkRequestList()) {

            if (workRequest instanceof DonorRegistrationRequest) {
                Object[] row = new Object[model.getColumnCount()];
                row[0] = workRequest;
                row[1] = formatter.format(((DonorRegistrationRequest) workRequest).getRequestDate());
                row[2] = ((DonorRegistrationRequest) workRequest).getName();
                row[3] = ((DonorRegistrationRequest) workRequest).getOrgType();
                row[4] = ((DonorRegistrationRequest) workRequest).getUserAddress();
                row[5] = ((DonorRegistrationRequest) workRequest).getUserContact();
                row[6] = ((DonorRegistrationRequest) workRequest).getUserEmailId();
                row[7] = ((DonorRegistrationRequest) workRequest).getStatus();

                model.addRow(row);
            }
        }

    }

}
